[package]
name = "sirius-hip"
version = "1.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-cors = "0.6"
clap = {version = "4.3", features = ["cargo"] }
log = "0.4"
env_logger = "0.10"
dotenv = "0.15"
once_cell = "1.21"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1.12"
serde-querystring-actix = "0.2.0"
erased-serde = "0.3"

toml = "0.7"
regex = "1.8"
chrono = { version = "0.4.26", features = ["serde"] }
jsonwebtoken = "8.3"

anyhow = "1.0"
thiserror = "1.0"

sqlx = { version = "0.7", features = [ "runtime-tokio", "mysql", "postgres", "chrono" ] }
sqlformat = "0.2"
uuid = { version = "1.20.0", features = ["v4"] }

mongodb = "3.5.0"

quick-xml = "0.28"
crc32fast = "1.3.2"
reqwest = { version = "0.11", features = [ "stream" ] }

dicom-object = "= 0.6.1"
dicom-encoding = "^0.6.0"
dicom-dictionary-std = "^0.6.0"
dicom-transfer-syntax-registry = "^0.6.0"
dicom-core = "^0.6.1"
dicom-json = "0.1.0"

tokio = { version = "1" }
tokio-stream = "0.1.14"
tokio-util = { version = "0.7", features = ["io"] }
futures = "0.3"
async-stream = "0.3.3"
async-trait = "0.1.89"

sha2 = "0.10"