services:

  # -- PACS 1 -------------------------------------------------------- #
  opendicom_pacs1_db:
    container_name: opendicom_pacs1_db
    image: mysql:5.7
    environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=pacsdb1
       - MYSQL_USER=pacs1
       - MYSQL_PASSWORD=pacs1
    restart: unless-stopped
    volumes:
        - ./service_pacs1/database/data:/var/lib/mysql
        - ./service_pacs1/database/entrypoint:/docker-entrypoint-initdb.d/
        - ./service_pacs1/database/conf:/etc/mysql/conf.d
    ports:
      - 0.0.0.0:13306:3306
    networks:
      - opendicom_net

  opendicom_pacs1:
    container_name: opendicom_pacs1
    image: opendicom/dcm4chee:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pacsdb1
      - MYSQL_USER=pacs1
      - MYSQL_PASSWORD=pacs1
      - MYSQL_HOST=opendicom_pacs1_db
      - MYSQL_PORT=3306
    restart: unless-stopped
    depends_on:
      - opendicom_pacs1_db
    volumes:
      - ./service_pacs1/default/:/opt/dcm4chee/server/default/
      - ./service_pacs1/archive/:/archive/
    ports:
      - 0.0.0.0:18080:8080
      - 0.0.0.0:11112:11112
      - 0.0.0.0:12575:2575
    logging:
      driver: json-file
      options:
        max-size: 100k
        max-file: "1"
    networks:
      - opendicom_net

  # -- PACS 2 -------------------------------------------------------- #
  opendicom_pacs2_db:
    container_name: opendicom_pacs2_db
    image: mysql:5.7
    environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=pacsdb2
       - MYSQL_USER=pacs2
       - MYSQL_PASSWORD=pacs2
    restart: unless-stopped
    volumes:
        - ./service_pacs2/database/data:/var/lib/mysql
        - ./service_pacs2/database/entrypoint:/docker-entrypoint-initdb.d/
        - ./service_pacs2/database/conf:/etc/mysql/conf.d
    ports:
      - 0.0.0.0:23306:3306
    networks:
      - opendicom_net

  opendicom_pacs2:
    container_name: opendicom_pacs2
    image: opendicom/dcm4chee:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pacsdb2
      - MYSQL_USER=pacs2
      - MYSQL_PASSWORD=pacs2
      - MYSQL_HOST=opendicom_pacs2_db
      - MYSQL_PORT=3306
    restart: unless-stopped
    depends_on:
      - opendicom_pacs2_db
    volumes:
      - ./service_pacs2/default/:/opt/dcm4chee/server/default/
      - ./service_pacs2/archive/:/archive/
    ports:
      - 0.0.0.0:28080:8080
      - 0.0.0.0:21112:11112
      - 0.0.0.0:22575:2575
    logging:
      driver: json-file
      options:
        max-size: 100k
        max-file: "1"
    networks:
      - opendicom_net

  # opendicom_ohif:
  #   image: ohif/app:v3.11.0
  #   container_name: opendicom_ohif
  #   depends_on:
  #     - opendicom_pacs1
  #     - opendicom_pacs2
  #   volumes:
  #     - ./service_ohif/app-config.js:/usr/share/nginx/html/app-config.js
  #   ports:
  #     - 3000:80
  
  # opendicom_sirius_hip:
  #   container_name: opendicom_sirius_hip
  #   image: opendicom/sirius-hip:latest
  #   env_file:
  #     - ./docker-compose.dev.env
  #   volumes:
  #     - ./service_pacs1/archive/:/DICOM/archive/
  #   ports:
  #     - 0.0.0.0:5001:5001
  #     - 0.0.0.0:5002:80
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: 100k
  #       max-file: "1"
  #   networks:
  #     - opendicom_net

networks:
  opendicom_net:
    name: opendicom_net