version: '3'
services:
  opendicom_pacs_db:
    container_name: opendicom_pacs_db
    image: mysql:5.7
    env_file:
      - ./docker-compose.env
      - ./docker-compose.dev.env
    restart: unless-stopped
    # healthcheck:
    #   test: mysql -sN --user="$$MYSQL_USER" --password="$$MYSQL_PASSWORD" $$MYSQL_DATABASE -e 'SELECT COUNT(*) FROM users' || exit 1
    #   start_period: 10s
    #   interval: 30s
    #   timeout: 5s
    #   retries: 10
    volumes:
        - ./service_pacs/database/data:/var/lib/mysql
        - ./service_pacs/database/entrypoint:/docker-entrypoint-initdb.d/
    ports:
      - 0.0.0.0:3306:3306
    networks:
      - opendicom_net

  opendicom_pacs:
    container_name: opendicom_pacs
    image: opendicom/dcm4chee:latest
    env_file:
      - ./docker-compose.env
      - ./docker-compose.dev.env
    restart: unless-stopped
    # healthcheck:
    #   test: curl --silent --fail http://localhost:8080/dcm4chee-web3 || exit 1
    #   start_period: 20s
    #   interval: 30s
    #   timeout: 5s
    #   retries: 10
    # depends_on:
    #   opendicom_pacs_db:
    #     condition: service_healthy
    #     restart: true
    volumes:
      - ./service_pacs/default/:/opt/dcm4chee/server/default/
      - ./service_pacs/archive/:/archive/
    ports:
      - 0.0.0.0:8080:8080
      - 0.0.0.0:11112:11112
      - 0.0.0.0:2575:2575
    logging:
      driver: json-file
      options:
        max-size: 100k
        max-file: "1"
    networks:
      - opendicom_net

  opendicom_ohif:
    image: ohif/app:v3.7.0
    container_name: opendicom_ohif
    depends_on:
      - opendicom_pacs
    volumes:
      - ./service_ohif/app-config.js:/usr/share/nginx/html/app-config.js
    ports:
      - 3000:80
  
  opendicom_sirius_hip:
    container_name: opendicom_sirius_hip
    image: opendicom/sirius-hip:latest
    env_file:
      - ./docker-compose.env
      - ./docker-compose.dev.env
    depends_on:
      opendicom_pacs:
        condition: service_healthy
        restart: true
    volumes:
      - ./service_pacs/archive/:/DICOM/archive/
    ports:
      - 0.0.0.0:5001:5001
      - 0.0.0.0:5002:80
    logging:
      driver: json-file
      options:
        max-size: 100k
        max-file: "1"
    networks:
      - opendicom_net

networks:
  opendicom_net:
    name: opendicom_net